import ClientProvider from "./ClientProvider";
import Header from "./Header";
import PromptInput from "./PromptInput";
import Providers from "./Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />

          <ClientProvider />

          {children}
        </Providers>
      </body>
    </html>
  );
}
